title: My awesome title
author: Ayden Murray
email: aydenjmurray@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  This will be a cool thing one day, I'm sure of it!
  If only I had some content...

# social links
twitter_username: aydenjm
instagram_username: aydenjm
github_username:  AydenMurray97

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
